apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: jio
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
    type: DirectoryOrCreate  # Ensures that the directory is created if it doesn't exist

