apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
  namespace: jio
spec: 
  accessModes:  
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Uncomment if you're using a specific storage class, but for default, leave it empty.
  # storageClassName: ""

