apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: jio  # Updated namespace to jio
  labels:
    role: api
    env: demo
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector: 
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: api
        image: asia-south1-docker.pkg.dev/dev-env-444307/demo/backend:v1  # Your backend image from GCR
        imagePullPolicy: Always
        env:
          - name: MONGO_CONN_STR
            value: "mongodb://mongodb-svc.jio.svc.cluster.local:27017/todo?directConnection=true"  # Correct MongoDB service URL
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
        ports:
        - containerPort: 3500
        livenessProbe: 
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1

